name: My Workflow
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync ArgoCD Application
        uses: omegion/argocd-actions@v1
        with:
          address: "https://34.134.117.44"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "sampl-app-18th-nov-24"