name: CI/CD with Argo CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Argo CD
    - name: Login to Argo CD
      uses: argoproj/argocd-login-action@v1.2.0
      with:
        username: ${{ secrets.ARGOCD_USERNAME }}
        password: ${{ secrets.ARGOCD_PASSWORD }}
        server: ${{ secrets.ARGOCD_SERVER }}

    # Step 3: Sync the application
    - name: Argo CD Sync
      uses: argoproj/argocd-app-sync-action@v1.0.0
      with:
        app: sampl-app-18th-nov-24/k8s-manifests
        prune: true
        force: true
